disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - identifier_name
  - line_length
  - nesting
  - trailing_whitespace
  - unused_closure_parameter

included: # paths to include during linting. `--path` is ignored if present.
  - FunJCamLib
  - FunJCam
  - FunJCamTests
  - FunJCamUITests

