platform :ios, '10.0'
use_frameworks!

target 'FunJCam' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'ModelMapper'
    pod 'ObjectMapper'
    pod 'RealmSwift'
    pod 'SDWebImage'

end

target 'FunJCamTests' do

end

target 'FunJCamUITests' do

end
