name: Run Tests on main branch.

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: xcodebuild test -project FunJCam.xcodeproj -scheme FunJCam -destination "platform=iOS Simulator,name=iPhone 13"
